# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"

  config.vm.synced_folder '../../', '/etc/puppet/modules/xtreemfs'

  config.vm.define :master do |master|
    # Setting a hostname
    master.vm.hostname = 'master.vagrant.dev'

    # Provider configuration
    master.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus   = 1
    end

    # A puppet server provision
    master.vm.provision :puppet do |puppet|
      puppet.manifests_path = '.'
      puppet.manifest_file  = 'prepare.pp'
    end

    # A puppet server provision
    master.vm.provision :puppet do |puppet|
      puppet.manifests_path = '..'
      puppet.manifest_file  = 'allinone.pp'
    end
  end
end
